name: flutter_wicc
description: Wikichain wallet library.
author: xinshuhao <xinshuhao@sina.cn>
homepage: https://github.com/xinshuhao
documentation: https://github.com/xinshuhao/wicc-wallet-utils-flutter/blob/master/test/wicc_test.dart
version: 1.0.2+1

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  pointycastle: ^1.0.1
  hex: ^0.1.2
  bs58check: ^1.0.1
  meta: ^1.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.1